<div class="row">	
	<h1>Crear Seguidor</h1>
	<?= Form::openMultipart() ?>
	<?php View::content() ?>
	<div class="col-lg-6">
		<?php echo Form::open() ?>
			<?= Form::hidden('seguidor.id') ?>
			<div class="form-group">
				<label>Nombre</label>
					<?php echo Form::text("seguidor.nombre","class='form-control'") ?>
			</div>
			<div class="form-group">
				<label>Nickname</label>
					<?php echo Form::text("seguidor.nombre_usr","class='form-control'") ?>
			</div>
			
		<?php echo Form::submit("Aceptar","class='btn btn-default'") ?>
		<?php echo Form::close() ?>
	</div>
</div>