<!-- <h1>MENU</h1> -->
<div class="navbar">
    <?= Html::linkAction("../artista/", 'Inicio') ?>
    <div class="dropdown">
        <button class="dropbtn">Perfil 
          <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content">
            <?= Html::linkAction("../artista/edit/1", 'Editar Perfil') ?>
            <?= Html::linkAction("../artista/update_photo/1", 'Actualizar Foto') ?>
        </div>
    </div>
    <div class="dropdown">
        <button class="dropbtn">Eventos 
          <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content">
            <?= Html::linkAction("../evento/create/", 'Crear Nuevo') ?>
            <?= Html::linkAction("../evento/listar", 'Listar Todos') ?>
        </div>
    </div> 
    <div class="dropdown">
        <button class="dropbtn">Publicación 
          <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content">
            <?= Html::linkAction("../publicacion/create/1", 'Crear Publicación') ?>
        </div>
    </div> 
    <div class="dropdown">
        <button class="dropbtn">Críticas de Contenido 
          <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content">
            <?= Html::linkAction("../critica/index/", 'Ver todas') ?>
        </div>
    </div> 
</div>

<?php View::content() ?>
<?php if (count($data) > 0) { ?>
    <table class="u-full-width">
        <thead>
            <tr>            
                <th>Nombre</th>
                <th>Lugar</th>
                <th>Fecha</th>
                <th>Hora</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody> 
            <?php foreach ($data as $item) { ?> 
                <tr>
                    <td><?= $item->nombre ?></td>
                    <td><?= $item->lugar ?></td>
                    <td><?= $item->fecha ?></td>
                    <td><?= $item->hora ?></td>
                    <td><?= Html::linkAction("edit/$item->id", 'Editar') ?></td>
                </tr> 
            <?php } ?>        
        </tbody>
    </table>
<?php } else { ?>
    <h2>No hay ningún registro</h2>
<?php } ?>