<h1>Lista de artistas</h1>
<?php View::content() ?>
<?php if (count($data) > 0) { ?>
    <table class="u-full-width">
        <thead>
            <tr>            
                <th>Nombre</th>
                <th>Nombre Artistico</th>
                <th>Biografía</th>
                <th>Influencias</th>
                <th>Edad</th>
                <th>Correo</th>
                <th>Foto</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody> 
            <?php foreach ($data as $item) { ?> 
                <tr>
                    <td><?= $item->nombre ?></td>
                    <td><?= $item->nombre_art ?></td>
                    <td><?= $item->bio ?></td>
                    <td><?= $item->inf ?></td>
                    <td><?= $item->edad ?></td>
                    <td><?= $item->email ?></td>
                    <td><?= $item->foto ?> </td>
                    <td><?= Html::linkAction("edit/$item->id", 'Editar') ?> | <?= Html::linkAction("update_photo/$item->id", 'Actualizar foto') ?></td>
                </tr> 
            <?php } ?>        
        </tbody>
    </table>
<?php } else { ?>
    <h2>No hay ningún registro</h2>
<?php } ?>