<!-- <h1>Actualizar Foto</h1> -->
<?php View::content() ?>

<!-- <h1>MENU</h1> -->
<div class="navbar">
    <a class="active" href="../artista/index">Inicio</a>
    <div class="dropdown">
        <button class="dropbtn">Perfil 
          <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content">
            <?= Html::linkAction("edit/1", 'Editar Perfil') ?>
            <?= Html::linkAction("update_photo/1", 'Actualizar Foto') ?>
        </div>
    </div>
    <div class="dropdown">
        <button class="dropbtn">Eventos 
          <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content">
            <?= Html::linkAction("../evento/create/", 'Crear Nuevo') ?>
            <?= Html::linkAction("../evento/listar", 'Listar Todos') ?>
        </div>
    </div> 
    <div class="dropdown">
        <button class="dropbtn">Publicación 
          <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content">
            <?= Html::linkAction("../publicacion/create/1", 'Crear Publicación') ?>
        </div>
    </div> 
    <div class="dropdown">
        <button class="dropbtn">Críticas de Contenido 
          <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content">
            <?= Html::linkAction("../critica/index/", 'Ver todas') ?>
        </div>
    </div> 
</div>

    <div class="row">
        <div class="six columns">
        <?= Html::img("upload/{$artista->foto}") ?>
    </div>
    <div class="row">
        <div class="six columns">
            <label for="artista_name">Nombre</label>
            <?= Form::text('artista.nombre', 'class="u-full-width" disabled') ?>        
        </div>   
    </div>
    <div class="row">
        <div class="six columns">
            <label for="artista_name_art">Nombre Artístico</label>
            <?= Form::text('artista.nombre_art', 'class="u-full-width" disabled') ?>        
        </div>   
    </div>
    <div class="row">
        <div class="six columns">
            <texta for="artista_bio">Biografía</label>
            <?= Form::textarea('artista.bio', 'class="u-full-width" disabled') ?>        
        </div>   
    </div>
    <div class="row">
        <div class="six columns">
            <label for="artista_inf">Influencias</label>
            <?= Form::text('artista.inf', 'class="u-full-width" disabled') ?>        
        </div>   
    </div>
    <div class="row">    
        <div class="six columns">
            <label for="artista_email">Correo electrónico</label>
            <?= Form::email('artista.email','class="u-full-width" disabled') ?>
        </div>
    </div>
    <div class="row">
        <div class="six columns">
            <label for="artista_age">Edad</label>
            <?= Form::number('artista.edad', 'class="u-full-width" disabled') ?>        
        </div>   
    </div>
    <?= Form::openMultipart() ?>
    <?= Form::hidden('artista.id') ?>
    <div class="row">
        <div class="six columns">
            <div class="row">
                <div class="six columns">
                    <label for="foto">Seleccionar otra foto</label>
                    <?= Form::file('foto') ?>        
                </div>   
            </div>    
        </div>   
    </div>
<input class="button-primary" value="Actualizar" type="submit">
<?= Form::close() ?>



